source 'https://rubygems.org'

ruby '2.4.0'

gem 'capybara'
gem 'data_mapper'
gem 'database_cleaner'
gem 'dm-postgres-adapter'
gem 'rspec'
gem 'rubocop'
gem 'simplecov'
gem 'simplecov-console'
gem 'sinatra'
gem 'sinatra-cross_origin'
